<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>Yuffster_rabidrunner2</title>
  <style type="text/css">
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
  </style>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
<p>By default, tests are considered failures when they raise an exception by using either a throw statement or the provided Test::assert method.</p>
<p>See the section on advanced handler methods for the exception to this rule.</p>
<h1 id="before-and-after-methods">Before and After Methods</h1>
<p>Each Test class supports four methods: before, after, beforeEach and afterEach.</p>
<p>Overriding these methods will result the method being run before the entire series of tests, after the entire series of test, before each test or after each test.</p>
<h1 id="advanced-handler-methods">Advanced Handler Methods</h1>
<p>Special handlers can be defined by creating a method on the TestRunner class beginning with ‘handle_’ and followed by a set of alphanumeric characters describing the condition. Any test methods beginning with handle_should_{condition} will be delegated to the specified handler method.</p>
<p>The handler method will be passed the Exception object from the run of the test method invoking it, or null if no Exception was caught.</p>
<p>If this handler method returns a string or true value, the result it is testing will be considered a failure, and the string will be recorded as the error message. If the handler method returns a null or false value, the result will be considered a success.</p>
<p>For example, included with the TestRunner class is the method named ‘handle_should_fail’:</p>
<pre><code>protected function handle_should_fail($error) {
    if (!$error) return &quot;Failed to throw an exception.&quot;;
}</code></pre>
<p>This method would result in the following test PASSING:</p>
<pre><code>public function should_fail_on_bad_math() {
    $this-&gt;assert(1==2, &quot;One is equal to two.&quot;);
}</code></pre>
<p>The success or failure of any methods in a Test class beginning with ‘should_fail’ will be determined by the result of this method.</p>
<p>As another example, let’s say that we were testing an alarm system. For several of our tests, we need to know whether the system is currently buzzing to alert people nearby.</p>
</body>
</html>
